### ISSUE TITLE
[Feature Request] Re-order firefox tab order to match container tabs sidebar tabs' order

### ISSUE THREAD

**Issue by juicetin** [maciekmm/container-tabs-sidebar#111]
First off thanks so much for this extension! Combined with FF's container functionality, it's _the_ functional reason that I stick to FF - being able to view my tabs in the sidebar, and have them grouped by container.

I think this is a feature request, and not something that's possible already - it would be great to be able to either
* automatically keep the browser's tab order matching that of the tabs in the containers (e.g. so that cycling to the next tab in the last one of a container, will take me to the first tab of the next container, as it is observed in the container tabs sidebar)
* achieve the above, but by way of a manual re-ordering, if it's a visually expensive/laggy UI process via the browser's native APIs

If this is something you're not particularly interested in implementing in the near future, but have a rough idea of how you might tackle it, I'd be happy to take a crack at it with some pointers from you as well!

Cheers 🙂

**Comment by maciekmm** [comment]
Hi @juicetin,
thank you for the kind words.

I believe what you are asking is already implemented under _Cycle tabs in view order_ setting. To activate it, navigate to `about:addons`, click preferences on the addon, select the checkbox and click save.

The reason it might not be enabled by default is due to a small performance hit that is measurable when you have hundreds of tabs open.

If you are interested, the implementation is available here: https://github.com/maciekmm/container-tabs-sidebar/blob/master/src/sidebar/tab_order_keeper.js

**Comment by juicetin** [comment]
Hi @maciekmm, whoops I totally didn't realise that's what the setting did - not sure what I thought it _did_ do. Thanks for that, the only small UX improvement I had in mind for the addon is now completely gone/resolved!
