### ISSUE TITLE
retain container collapse after re-opening sidebar

### ISSUE THREAD

**Issue by maciekmm** [maciekmm/container-tabs-sidebar#35]

**Comment by thomasfinstad** [comment]
The re-expanding containers on re-opening of the sidebar currently makes it so I can't really use it on my laptop which has a screen too small for the sidebar to always be open. And since it also shows containers from other windows that I need to split the tabs due to the re expanding it is not floating my boat currently. :+1: on this issue.

**Comment by maciekmm** [comment]
@thomasfinstad will be out with the next release ;)
