### ISSUE TITLE
Auto-assign tabs to containers

### ISSUE THREAD

**Issue by matkoch** [maciekmm/container-tabs-sidebar#45]
_First off, really great work! And I'm especially happy that there is active development. I used PowerTabs before, but this one is more appealing. However..._ 😄 

PowerTabs had the ability to auto-assign tabs based their domain. A similar functionality would be great! From my point of view, regexes on the title would be even better.

**Comment by maciekmm** [comment]
Thank You :100: 
PowerTobs works in a bit different way, it does not use firefox's privacy containers (contextualIdentities).

Because we are using contextual identities many people will have either:
- [Multi-Account containers](https://addons.mozilla.org/pl/firefox/addon/multi-account-containers/) which provides assignments per domain basis or
- [Containerise](https://addons.mozilla.org/pl/firefox/addon/containerise/) which provides regex based assignment
- or any other addon with similar features
installed.

Container Tabs Sidebar works well with any extension that assigns the tab to a specific container. That's why I don't want to incorporate assigning logic to CTS, which is purely presentational addon.
 
Because reassigning tab requires the whole page to be reloaded (because of the different cookie store) the regex on titles would be a bit cumbersome, heavy and probably frustrating.

**Comment by maciekmm** [comment]
I could add a _assign current tab to this container_ option to the context menu to provide a interoperation with Multi-Account containers.
